package presentacion;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import logica.DTCategoria;
import logica.Fabrica;
import logica.IControladorSistema;
import logica.Status;

import javax.swing.*;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import java.awt.*;
import java.util.Set;

/**
 * Contenido de la ventana interna "Alta de Categoria". El diseño esta en
 * AltaCategoria.form (editable por arrastre); esta clase contiene el
 * comportamiento.
 * <p>
 * Flujo (DSS Categoria):
 * 1) listarCategorias() -> arma el arbol con las categorias existentes
 * 2) altaCategoria(nombre) -> OK: se agrega al arbol; ERROR (ya existe): se
 *    avisa por dialogo y la ventana queda abierta para reingresar o cancelar
 *    (LOOP del DSS).
 */
public class AltaCategoria {

    private JTextField NombreTxt;
    private JTree CategoriasTree;
    private JPanel mainPanel;
    private JButton cancelarButton;
    private JButton aceptarButton;

    private final transient IControladorSistema controlador;
    private transient Runnable accionCerrar = () -> {
    };

    public AltaCategoria() {
        controlador = Fabrica.getInstancia().getControladorSistema();

        recargarArbol();

        aceptarButton.addActionListener(e -> aceptar());
        cancelarButton.addActionListener(e -> accionCerrar.run());
    }

    public JPanel getMainPanel() {
        return mainPanel;
    }

    /** Define que hacer cuando el panel pide cerrarse (lo decide la ventana principal). */
    public void setAccionCerrar(Runnable accionCerrar) {
        this.accionCerrar = accionCerrar;
    }

    /**
     * Arma el arbol de categorias: un nodo raiz "Categorias" y una hoja por
     * cada categoria existente. Se llama al inicio y despues de cada alta OK,
     * para que el arbol refleje la nueva categoria.
     */
    private void recargarArbol() {
        // listarCategorias() : set<DTCategoria>
        DefaultMutableTreeNode raiz = new DefaultMutableTreeNode("Categorias");
        for (DTCategoria c : controlador.listarCategorias()) {
            raiz.add(new DefaultMutableTreeNode(c.getNombre()));
        }
        CategoriasTree.setModel(new DefaultTreeModel(raiz));
        // Expandir para que se vean las categorias colgando de la raiz.
        for (int i = 0; i < CategoriasTree.getRowCount(); i++) {
            CategoriasTree.expandRow(i);
        }
    }

    private void aceptar() {
        String nombre = NombreTxt.getText().trim();
        if (nombre.isEmpty()) {
            JOptionPane.showMessageDialog(mainPanel, "Ingresá el nombre de la categoría.",
                    "Alta de Categoría", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // altaCategoria(nombre) : Status
        Status resultado = controlador.altaCategoria(nombre);
        if (resultado == Status.OK) {
            recargarArbol();      // el arbol refleja la nueva categoria
            NombreTxt.setText("");
            JOptionPane.showMessageDialog(mainPanel, "Categoría creada con éxito.",
                    "Alta de Categoría", JOptionPane.INFORMATION_MESSAGE);
        } else {
            // ERROR: ya existe una categoria con ese nombre. Se avisa y se deja
            // la ventana abierta para reingresar o cancelar (LOOP del DSS).
            JOptionPane.showMessageDialog(mainPanel,
                    "Ya existe una categoría con ese nombre.",
                    "Alta de Categoría", JOptionPane.WARNING_MESSAGE);
        }
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new GridLayoutManager(5, 2, new Insets(0, 0, 0, 0), -1, -1));
        final JLabel label1 = new JLabel();
        label1.setText("Nombre de la nueva categoria");
        mainPanel.add(label1, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label2 = new JLabel();
        label2.setText("Categorias Existentes");
        mainPanel.add(label2, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        NombreTxt = new JTextField();
        mainPanel.add(NombreTxt, new GridConstraints(3, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_GROW | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, new Dimension(150, -1), null, 0, false));
        final JScrollPane scrollPane1 = new JScrollPane();
        mainPanel.add(scrollPane1, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, new Dimension(-1, 120), null, null, 0, false));
        CategoriasTree = new JTree();
        scrollPane1.setViewportView(CategoriasTree);
        final JLabel label3 = new JLabel();
        label3.setText("Alta Categoria");
        mainPanel.add(label3, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        cancelarButton = new JButton();
        cancelarButton.setText("Cancelar");
        mainPanel.add(cancelarButton, new GridConstraints(4, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        aceptarButton = new JButton();
        aceptarButton.setText("Confirmar");
        mainPanel.add(aceptarButton, new GridConstraints(4, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer1 = new Spacer();
        mainPanel.add(spacer1, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, GridConstraints.SIZEPOLICY_CAN_SHRINK, GridConstraints.SIZEPOLICY_CAN_GROW | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }
}
