package presentacion;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import logica.DTAsistente;
import logica.DTRegistro;
import logica.DTUsuario;
import logica.Fabrica;
import logica.IControladorSistema;

import javax.swing.*;
import java.awt.*;
import java.util.Set;

/**
 * Contenido de la ventana interna "Consulta de Registro". El diseño esta en
 * ConsultaDeRegistro.form (editable por arrastre); esta clase contiene el
 * comportamiento. Es de solo lectura: no hay boton Confirmar, solo Cerrar.
 *
 * Flujo (DSS ConsultaRegistro):
 *  1) listarUsuarios()                  -> llena UsuarioCBox
 *  2) listarRegistroUsuario(nickname)   -> llena RegistroCBox
 *     (antes se llama seleccionarUsuario(nickname), que recuerda el asistente,
 *      porque listarRegistroUsuario() toma los registros del asistente recordado)
 *  3) obtenerRegistro(nickname, nombre) -> llena los campos de detalle
 */
public class ConsultaDeRegistro {

    private JComboBox UsuarioCBox;
    private JComboBox RegistroCBox;
    private JPanel mainPanel;
    private JTextField EdicionTxt;
    private JTextField TipoRegistroTxt;
    private JTextField CostoTxt;
    private JTextField FechaRegistroTxt;
    private JButton cerrarButton;
    private JLabel edicionLbl;
    private JLabel tipoRegistroLbl;
    private JLabel costoLbl;
    private JLabel fechaRegistroLbl;

    private final transient IControladorSistema controlador;
    private transient Runnable accionCerrar = () -> {
    };

    public ConsultaDeRegistro() {
        controlador = Fabrica.getInstancia().getControladorSistema();

        // Los campos de detalle son de solo lectura (es una consulta).
        EdicionTxt.setEditable(false);
        TipoRegistroTxt.setEditable(false);
        CostoTxt.setEditable(false);
        FechaRegistroTxt.setEditable(false);

        cargarUsuarios();

        UsuarioCBox.addActionListener(e -> cargarRegistros());
        RegistroCBox.addActionListener(e -> mostrarRegistro());
        cerrarButton.addActionListener(e -> accionCerrar.run());
    }

    public JPanel getMainPanel() {
        return mainPanel;
    }

    /** Define que hacer cuando el panel pide cerrarse (lo decide la ventana principal). */
    public void setAccionCerrar(Runnable accionCerrar) {
        this.accionCerrar = accionCerrar;
    }

    private void cargarUsuarios() {
        // listarUsuarios() : set<DTUsuario>
        Set<DTUsuario> usuarios = controlador.listarUsuarios();
        for (DTUsuario u : usuarios) {
            UsuarioCBox.addItem(u.getNickname());
        }
        cargarRegistros();
    }

    private void cargarRegistros() {
        RegistroCBox.removeAllItems();
        limpiarDetalle();

        String nickname = (String) UsuarioCBox.getSelectedItem();
        if (nickname == null) {
            return;
        }

        // seleccionarUsuario(nickname) -- Sistema retiene el asistente seleccionado,
        // del que listarRegistroUsuario() toma los registros.
        DTUsuario usuario = controlador.seleccionarUsuario(nickname);
        if (!(usuario instanceof DTAsistente)) {
            // Solo los asistentes tienen registros; un organizador no muestra nada.
            return;
        }

        // listarRegistroUsuario(nickname) : set<DTRegistro>
        Set<DTRegistro> registros = controlador.listarRegistroUsuario(nickname);
        for (DTRegistro r : registros) {
            RegistroCBox.addItem(r.getNombreEdicion());
        }
        mostrarRegistro();
    }

    private void mostrarRegistro() {
        String nickname = (String) UsuarioCBox.getSelectedItem();
        String nombreEdicion = (String) RegistroCBox.getSelectedItem();
        if (nickname == null || nombreEdicion == null) {
            limpiarDetalle();
            return;
        }

        // obtenerRegistro(nickname, nombre) : DTRegistro
        DTRegistro reg = controlador.obtenerRegistro(nickname, nombreEdicion);
        if (reg == null) {
            limpiarDetalle();
            return;
        }
        EdicionTxt.setText(reg.getNombreEdicion());
        TipoRegistroTxt.setText(reg.getTipoRegistro());
        CostoTxt.setText(String.valueOf(reg.getCosto()));
        FechaRegistroTxt.setText(String.valueOf(reg.getFechaRegistro()));
    }

    private void limpiarDetalle() {
        EdicionTxt.setText("");
        TipoRegistroTxt.setText("");
        CostoTxt.setText("");
        FechaRegistroTxt.setText("");
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new GridLayoutManager(8, 3, new Insets(0, 0, 0, 0), -1, -1));
        final JLabel label1 = new JLabel();
        label1.setText("Consulta de Registro");
        mainPanel.add(label1, new GridConstraints(0, 0, 1, 3, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        UsuarioCBox = new JComboBox();
        final DefaultComboBoxModel defaultComboBoxModel1 = new DefaultComboBoxModel();
        UsuarioCBox.setModel(defaultComboBoxModel1);
        mainPanel.add(UsuarioCBox, new GridConstraints(1, 2, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label2 = new JLabel();
        label2.setText("Usuario");
        mainPanel.add(label2, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        RegistroCBox = new JComboBox();
        final DefaultComboBoxModel defaultComboBoxModel2 = new DefaultComboBoxModel();
        RegistroCBox.setModel(defaultComboBoxModel2);
        mainPanel.add(RegistroCBox, new GridConstraints(2, 2, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label3 = new JLabel();
        label3.setText("Registro");
        mainPanel.add(label3, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        EdicionTxt = new JTextField();
        EdicionTxt.setText("");
        mainPanel.add(EdicionTxt, new GridConstraints(3, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        TipoRegistroTxt = new JTextField();
        mainPanel.add(TipoRegistroTxt, new GridConstraints(4, 2, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        CostoTxt = new JTextField();
        mainPanel.add(CostoTxt, new GridConstraints(5, 2, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        cerrarButton = new JButton();
        cerrarButton.setText("Cerrar");
        mainPanel.add(cerrarButton, new GridConstraints(7, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        edicionLbl = new JLabel();
        edicionLbl.setText("Edición");
        mainPanel.add(edicionLbl, new GridConstraints(3, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        tipoRegistroLbl = new JLabel();
        tipoRegistroLbl.setText("Tipo de Registro");
        mainPanel.add(tipoRegistroLbl, new GridConstraints(4, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        costoLbl = new JLabel();
        costoLbl.setText("Costo");
        mainPanel.add(costoLbl, new GridConstraints(5, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        fechaRegistroLbl = new JLabel();
        fechaRegistroLbl.setText("Fecha de Registro");
        mainPanel.add(fechaRegistroLbl, new GridConstraints(6, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        FechaRegistroTxt = new JTextField();
        FechaRegistroTxt.setText("");
        mainPanel.add(FechaRegistroTxt, new GridConstraints(6, 2, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }

}
