package presentacion;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import logica.DTEdicionEvento;
import logica.DTEvento;
import logica.DTFecha;
import logica.Fabrica;
import logica.IControladorSistema;

import javax.swing.*;
import java.awt.*;
import java.util.Set;

/**
 * Contenido de la ventana interna "Consulta de Evento". El diseño esta en
 * ConsultaEvento.form (editable por arrastre); esta clase contiene el
 * comportamiento. Es de solo lectura: no hay boton Confirmar, solo Cerrar.
 */
public class ConsultaEvento {

    private JPanel mainPanel;
    private JComboBox EventoCBox;
    private JTextField NombreTxt;
    private JTextField SiglaTxt;
    private JTextField DescripcionTxt;
    private JTextField FechaAltaTxt;
    private JComboBox EdicionCBox;
    private JTextField NombreEdicionTxt;
    private JTextField SiglaEdicionTxt;
    private JTextField CiudadTxt;
    private JTextField PaisTxt;
    private JTextField FechaInicioTxt;
    private JTextField FechaFinTxt;
    private JTextField FechaAltaEdicionTxt;
    private JButton cerrarButton;

    private final transient IControladorSistema controlador;
    private transient Runnable accionCerrar = () -> {
    };

    public ConsultaEvento() {
        controlador = Fabrica.getInstancia().getControladorSistema();

        cargarEventos();

        EventoCBox.addActionListener(e -> seleccionarEvento());
        EdicionCBox.addActionListener(e -> seleccionarEdicion());
        cerrarButton.addActionListener(e -> accionCerrar.run());
    }

    public JPanel getMainPanel() {
        return mainPanel;
    }

    /**
     * Define que hacer cuando el panel pide cerrarse (lo decide la ventana principal).
     */
    public void setAccionCerrar(Runnable accionCerrar) {
        this.accionCerrar = accionCerrar;
    }

    private void cargarEventos() {
        // consultarEvento() : set<DTEvento> -- reutiliza listarEventos()
        Set<DTEvento> eventos = controlador.listarEventos();
        for (DTEvento ev : eventos) {
            EventoCBox.addItem(ev.getNombre());
        }
        seleccionarEvento();
    }

    private void seleccionarEvento() {
        String nombreEvento = (String) EventoCBox.getSelectedItem();
        EdicionCBox.removeAllItems();
        limpiarDetalleEdicion();
        if (nombreEvento == null) {
            limpiarDetalleEvento();
            return;
        }

        // seleccionarEvento(nombreEvento) : DTEvento -- Sistema retiene eventoSeleccionado
        DTEvento evento = controlador.seleccionarEvento(nombreEvento);
        NombreTxt.setText(evento.getNombre());
        SiglaTxt.setText(evento.getSigla());
        DescripcionTxt.setText(evento.getDescripcion());
        FechaAltaTxt.setText(formatearFecha(evento.getFechaAlta()));

        // listarEdicionesDeEvento(nombreEvento) : set<DTEdicionEvento>
        Set<DTEdicionEvento> ediciones = controlador.listarEdicionesDeEvento(nombreEvento);
        for (DTEdicionEvento ed : ediciones) {
            EdicionCBox.addItem(ed.getNombre());
        }
        seleccionarEdicion();
    }

    private void seleccionarEdicion() {
        String nombreEdicion = (String) EdicionCBox.getSelectedItem();
        if (nombreEdicion == null) {
            limpiarDetalleEdicion();
            return;
        }

        // seleccionarEdicionEvento(nombreEdicion) : DTEdicionEvento
        DTEdicionEvento edicion = controlador.seleccionarEdicionEvento(nombreEdicion);
        NombreEdicionTxt.setText(edicion.getNombre());
        SiglaEdicionTxt.setText(edicion.getSigla());
        CiudadTxt.setText(edicion.getCiudad());
        PaisTxt.setText(edicion.getPais());
        FechaInicioTxt.setText(formatearFecha(edicion.getFechaInicio()));
        FechaFinTxt.setText(formatearFecha(edicion.getFechaFin()));
        FechaAltaEdicionTxt.setText(formatearFecha(edicion.getFechaAlta()));
    }

    private String formatearFecha(DTFecha fecha) {
        return fecha.getDia() + "/" + fecha.getMes() + "/" + fecha.getAnio();
    }

    private void limpiarDetalleEvento() {
        NombreTxt.setText("");
        SiglaTxt.setText("");
        DescripcionTxt.setText("");
        FechaAltaTxt.setText("");
    }

    private void limpiarDetalleEdicion() {
        NombreEdicionTxt.setText("");
        SiglaEdicionTxt.setText("");
        CiudadTxt.setText("");
        PaisTxt.setText("");
        FechaInicioTxt.setText("");
        FechaFinTxt.setText("");
        FechaAltaEdicionTxt.setText("");
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new GridLayoutManager(15, 2, new Insets(0, 0, 0, 0), -1, -1));
        final JLabel label1 = new JLabel();
        label1.setText("Consulta de Evento");
        mainPanel.add(label1, new GridConstraints(0, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label2 = new JLabel();
        label2.setText("Evento");
        mainPanel.add(label2, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        EventoCBox = new JComboBox();
        mainPanel.add(EventoCBox, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label3 = new JLabel();
        label3.setText("Nombre");
        mainPanel.add(label3, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        NombreTxt = new JTextField();
        NombreTxt.setEditable(false);
        NombreTxt.setText("");
        mainPanel.add(NombreTxt, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        final JLabel label4 = new JLabel();
        label4.setText("Sigla");
        mainPanel.add(label4, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        SiglaTxt = new JTextField();
        SiglaTxt.setEditable(false);
        mainPanel.add(SiglaTxt, new GridConstraints(3, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        final JLabel label5 = new JLabel();
        label5.setText("Descripción");
        mainPanel.add(label5, new GridConstraints(4, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        DescripcionTxt = new JTextField();
        DescripcionTxt.setEditable(false);
        mainPanel.add(DescripcionTxt, new GridConstraints(4, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        final JLabel label6 = new JLabel();
        label6.setText("Fecha de Alta");
        mainPanel.add(label6, new GridConstraints(5, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        FechaAltaTxt = new JTextField();
        FechaAltaTxt.setEditable(false);
        mainPanel.add(FechaAltaTxt, new GridConstraints(5, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        final JLabel label7 = new JLabel();
        label7.setText("Edición");
        mainPanel.add(label7, new GridConstraints(6, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        EdicionCBox = new JComboBox();
        mainPanel.add(EdicionCBox, new GridConstraints(6, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label8 = new JLabel();
        label8.setText("Nombre");
        mainPanel.add(label8, new GridConstraints(7, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        NombreEdicionTxt = new JTextField();
        NombreEdicionTxt.setEditable(false);
        mainPanel.add(NombreEdicionTxt, new GridConstraints(7, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        final JLabel label9 = new JLabel();
        label9.setText("Sigla");
        mainPanel.add(label9, new GridConstraints(8, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        SiglaEdicionTxt = new JTextField();
        SiglaEdicionTxt.setEditable(false);
        mainPanel.add(SiglaEdicionTxt, new GridConstraints(8, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        final JLabel label10 = new JLabel();
        label10.setText("Ciudad");
        mainPanel.add(label10, new GridConstraints(9, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        CiudadTxt = new JTextField();
        CiudadTxt.setEditable(false);
        mainPanel.add(CiudadTxt, new GridConstraints(9, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        final JLabel label11 = new JLabel();
        label11.setText("País");
        mainPanel.add(label11, new GridConstraints(10, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        PaisTxt = new JTextField();
        PaisTxt.setEditable(false);
        mainPanel.add(PaisTxt, new GridConstraints(10, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        final JLabel label12 = new JLabel();
        label12.setText("Fecha de Inicio");
        mainPanel.add(label12, new GridConstraints(11, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        FechaInicioTxt = new JTextField();
        FechaInicioTxt.setEditable(false);
        mainPanel.add(FechaInicioTxt, new GridConstraints(11, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        final JLabel label13 = new JLabel();
        label13.setText("Fecha Fin");
        mainPanel.add(label13, new GridConstraints(12, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        FechaFinTxt = new JTextField();
        FechaFinTxt.setEditable(false);
        mainPanel.add(FechaFinTxt, new GridConstraints(12, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        final JLabel label14 = new JLabel();
        label14.setText("Fecha de Alta");
        mainPanel.add(label14, new GridConstraints(13, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        FechaAltaEdicionTxt = new JTextField();
        FechaAltaEdicionTxt.setEditable(false);
        mainPanel.add(FechaAltaEdicionTxt, new GridConstraints(13, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        cerrarButton = new JButton();
        cerrarButton.setText("Cerrar");
        mainPanel.add(cerrarButton, new GridConstraints(14, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }

}
