package presentacion;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import logica.DTEdicionEvento;
import logica.DTEvento;
import logica.DTTipoRegistro;
import logica.Fabrica;
import logica.IControladorSistema;

import javax.swing.*;
import java.awt.*;
import java.util.Set;

public class VentanaConsultaTipoRegistro extends JInternalFrame {

    private JPanel mainPanel;
    private JComboBox eventoBox;
    private JComboBox edicionBox;
    private JComboBox registroBox;
    private JTextField nombreTxt;
    private JTextField descTxt;
    private JTextField costoTxt;
    private JTextField cupoTxt;
    private JButton botonCerrar;

    private final IControladorSistema controlador;

    public VentanaConsultaTipoRegistro() {
        super("Consulta de Tipo de Registro", true, true, true, true);

        controlador = Fabrica.getInstancia().getControladorSistema();

        setContentPane(mainPanel);
        pack();

        nombreTxt.setEditable(false);
        descTxt.setEditable(false);
        costoTxt.setEditable(false);
        cupoTxt.setEditable(false);

        cargarEventos();

        eventoBox.addActionListener(e -> cargarEdiciones());
        edicionBox.addActionListener(e -> cargarTiposRegistro());
        registroBox.addActionListener(e -> mostrarTipoRegistro());
        botonCerrar.addActionListener(e -> dispose());
    }

    private void cargarEventos() {
        for (DTEvento evento : controlador.listarEventos()) {
            eventoBox.addItem(evento.getNombre());
        }
        cargarEdiciones();
    }

    private void cargarEdiciones() {
        edicionBox.removeAllItems();
        registroBox.removeAllItems();
        limpiarDetalle();

        String nombreEvento = (String) eventoBox.getSelectedItem();
        if (nombreEvento == null) {
            return;
        }

        Set<DTEdicionEvento> ediciones =
                controlador.listarEdicionesDeEvento(nombreEvento);

        for (DTEdicionEvento edicion : ediciones) {
            edicionBox.addItem(edicion.getNombre());
        }
    }

    private void cargarTiposRegistro() {
        registroBox.removeAllItems();
        limpiarDetalle();

        String nombreEdicion = (String) edicionBox.getSelectedItem();
        if (nombreEdicion == null) {
            return;
        }

        Set<DTTipoRegistro> tipos =
                controlador.listarTiposRegistroDeEdicion(nombreEdicion);

        for (DTTipoRegistro tipo : tipos) {
            registroBox.addItem(tipo.getNombre());
        }
    }

    private void mostrarTipoRegistro() {
        String nombreTipo = (String) registroBox.getSelectedItem();
        if (nombreTipo == null) {
            limpiarDetalle();
            return;
        }

        DTTipoRegistro tipo =
                controlador.seleccionarTipoRegistro(nombreTipo);

        nombreTxt.setText(tipo.getNombre());
        descTxt.setText(tipo.getDescripcion());
        costoTxt.setText(String.valueOf(tipo.getCosto()));
        cupoTxt.setText(String.valueOf(tipo.getCupo()));
    }

    private void limpiarDetalle() {
        nombreTxt.setText("");
        descTxt.setText("");
        costoTxt.setText("");
        cupoTxt.setText("");
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new GridLayoutManager(10, 3, new Insets(0, 0, 0, 0), -1, -1));
        final JLabel label1 = new JLabel();
        label1.setText("Consulta de Tipo de Registro");
        mainPanel.add(label1, new GridConstraints(0, 0, 1, 2, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer1 = new Spacer();
        mainPanel.add(spacer1, new GridConstraints(0, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        final Spacer spacer2 = new Spacer();
        mainPanel.add(spacer2, new GridConstraints(9, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        final JLabel label2 = new JLabel();
        label2.setText("Evento:");
        mainPanel.add(label2, new GridConstraints(1, 0, 1, 2, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label3 = new JLabel();
        label3.setText("Edición:");
        mainPanel.add(label3, new GridConstraints(2, 0, 1, 2, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label4 = new JLabel();
        label4.setText("Tipo de registro:");
        mainPanel.add(label4, new GridConstraints(3, 0, 1, 2, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        eventoBox = new JComboBox();
        mainPanel.add(eventoBox, new GridConstraints(1, 2, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        edicionBox = new JComboBox();
        mainPanel.add(edicionBox, new GridConstraints(2, 2, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        registroBox = new JComboBox();
        mainPanel.add(registroBox, new GridConstraints(3, 2, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label5 = new JLabel();
        label5.setText("Datos del tipo de registro  ");
        mainPanel.add(label5, new GridConstraints(4, 0, 1, 2, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label6 = new JLabel();
        label6.setText("Nombre:");
        mainPanel.add(label6, new GridConstraints(5, 0, 1, 2, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label7 = new JLabel();
        label7.setText("Descripción:");
        mainPanel.add(label7, new GridConstraints(6, 0, 1, 2, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label8 = new JLabel();
        label8.setText("Costo:");
        mainPanel.add(label8, new GridConstraints(7, 0, 1, 2, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label9 = new JLabel();
        label9.setText("Cupo:");
        mainPanel.add(label9, new GridConstraints(8, 0, 1, 2, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        nombreTxt = new JTextField();
        nombreTxt.setEditable(false);
        mainPanel.add(nombreTxt, new GridConstraints(5, 2, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        descTxt = new JTextField();
        descTxt.setEditable(false);
        mainPanel.add(descTxt, new GridConstraints(6, 2, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        costoTxt = new JTextField();
        costoTxt.setEditable(false);
        mainPanel.add(costoTxt, new GridConstraints(7, 2, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        cupoTxt = new JTextField();
        cupoTxt.setEditable(false);
        mainPanel.add(cupoTxt, new GridConstraints(8, 2, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        botonCerrar = new JButton();
        botonCerrar.setText("Cerrar");
        mainPanel.add(botonCerrar, new GridConstraints(9, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }

}
