package presentacion;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;

import logica.Fabrica;
import logica.IControladorSistema;
import logica.Status;
import logica.DTCategoria;

import javax.swing.*;
import java.awt.*;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import java.util.Set;

public class VentanaAltaEvento extends JInternalFrame {
    private JPanel mainPanel;
    private JTextField nombretxt;
    private JTextField desctxt;
    private JTextField fechatxt;
    private JTextField siglatxt;
    private JList<String> catlist;
    private JButton aceptarButton;
    private JButton cancelarButton;

    private final IControladorSistema controlador;

    public VentanaAltaEvento() {
        super("Alta de Evento", true, true, true, true);
        controlador = Fabrica.getInstancia().getControladorSistema();

        // 🔹 Cargar categorías en el JList (solo nombres)
        Set<DTCategoria> categorias = controlador.listarCategorias();
        List<String> nombresCategorias = new ArrayList<>();

        for (DTCategoria c : categorias) {
            nombresCategorias.add(c.getNombre()); // usa el getter del DTO
        }

        catlist.setListData(nombresCategorias.toArray(new String[0]));

        aceptarButton.addActionListener(e -> aceptar());
        cancelarButton.addActionListener(e -> dispose());

        setContentPane(mainPanel);
        pack();
    }

    private void aceptar() {
        String nombre = nombretxt.getText().trim();
        String descripcion = desctxt.getText().trim();
        String fechaStr = fechatxt.getText().trim();
        String sigla = siglatxt.getText().trim();

        // Validaciones básicas
        if (nombre.isEmpty() || descripcion.isEmpty() || fechaStr.isEmpty() || sigla.isEmpty()) {
            JOptionPane.showMessageDialog(mainPanel, "Completá todos los campos.", "Datos incompletos", JOptionPane.WARNING_MESSAGE);
            return;
        }

        LocalDate fechaAlta;
        try {
            fechaAlta = LocalDate.parse(fechaStr); // formato ISO yyyy-MM-dd
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(mainPanel, "Formato de fecha inválido (use yyyy-MM-dd).", "Error de fecha", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Obtener categorías seleccionadas
        List<String> nombresCategorias = catlist.getSelectedValuesList();
        if (nombresCategorias.isEmpty()) {
            JOptionPane.showMessageDialog(mainPanel, "Debe seleccionar al menos una categoría.", "Categorías requeridas", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Llamada al sistema
        Status resultado = controlador.ingresarDatosEvento(nombre, descripcion, fechaAlta, sigla, nombresCategorias);

        if (resultado == Status.OK) {
            JOptionPane.showMessageDialog(mainPanel, "Evento dado de alta correctamente.", "Alta de evento", JOptionPane.INFORMATION_MESSAGE);
            dispose();
        } else {
            JOptionPane.showMessageDialog(mainPanel, "Ya existe un evento con el nombre \"" + nombre + "\".", "Nombre en uso", JOptionPane.WARNING_MESSAGE);
            nombretxt.requestFocus();
            nombretxt.selectAll();
        }
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new GridLayoutManager(7, 2, new Insets(0, 0, 0, 0), -1, -1));
        final JLabel label1 = new JLabel();
        label1.setText("Nombre del evento");
        mainPanel.add(label1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer1 = new Spacer();
        mainPanel.add(spacer1, new GridConstraints(6, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        nombretxt = new JTextField();
        nombretxt.setText("");
        mainPanel.add(nombretxt, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        final JLabel label2 = new JLabel();
        label2.setText("Descripción");
        mainPanel.add(label2, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label3 = new JLabel();
        label3.setText("Fecha de Alta");
        mainPanel.add(label3, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label4 = new JLabel();
        label4.setText("Sigla");
        mainPanel.add(label4, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label5 = new JLabel();
        label5.setText("Categorías");
        mainPanel.add(label5, new GridConstraints(4, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        desctxt = new JTextField();
        desctxt.setText("");
        mainPanel.add(desctxt, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        fechatxt = new JTextField();
        mainPanel.add(fechatxt, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        siglatxt = new JTextField();
        siglatxt.setText("");
        mainPanel.add(siglatxt, new GridConstraints(3, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        aceptarButton = new JButton();
        aceptarButton.setText("Aceptar");
        mainPanel.add(aceptarButton, new GridConstraints(5, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        cancelarButton = new JButton();
        cancelarButton.setText("Cancelar");
        mainPanel.add(cancelarButton, new GridConstraints(5, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        catlist = new JList();
        mainPanel.add(catlist, new GridConstraints(4, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(150, 50), null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }
}
