package presentacion;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import logica.Fabrica;
import logica.IControladorSistema;
import logica.Status;

import javax.swing.*;
import java.awt.*;

public class VentanaAltaInstitucion extends JInternalFrame {

    // Variables del formulario
    private JPanel mainPanel;
    private JTextField nombre;
    private JTextField desc;
    private JTextField sitioWeb;
    private JButton aceptarButton;
    private JButton cancelarButton;

    private final IControladorSistema controlador;

    public VentanaAltaInstitucion() {
        super("Alta de Institución", true, true, true, true);

        controlador = Fabrica.getInstancia().getControladorSistema();

        // Configuración de listeners
        aceptarButton.addActionListener(e -> aceptar());
        cancelarButton.addActionListener(e -> dispose());

        setContentPane(mainPanel);
        pack();
    }

    private void aceptar() {
        String nombreInstitucion = nombre.getText().trim();
        String descripcion = desc.getText().trim();
        String web = sitioWeb.getText().trim();

        if (nombreInstitucion.isEmpty()
                || descripcion.isEmpty()
                || web.isEmpty()) {

            JOptionPane.showMessageDialog(
                    mainPanel,
                    "Completá todos los campos.",
                    "Datos incompletos",
                    JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        // Llamada con Strings, no con DTO
        Status resultado = controlador.altaInstitucion(
                nombreInstitucion,
                descripcion,
                web
        );

        if (resultado == Status.OK) {
            JOptionPane.showMessageDialog(
                    mainPanel,
                    "Institución dada de alta correctamente.",
                    "Alta de institución",
                    JOptionPane.INFORMATION_MESSAGE
            );
            dispose(); // o accionCerrar.run();

        } else {
            JOptionPane.showMessageDialog(
                    mainPanel,
                    "Ya existe una institución con el nombre \""
                            + nombreInstitucion + "\".",
                    "Nombre en uso",
                    JOptionPane.WARNING_MESSAGE
            );
            nombre.requestFocus();
            nombre.selectAll();
        }
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new GridLayoutManager(5, 2, new Insets(0, 0, 0, 0), -1, -1));
        final JLabel label1 = new JLabel();
        label1.setText("Nombre:");
        mainPanel.add(label1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer1 = new Spacer();
        mainPanel.add(spacer1, new GridConstraints(4, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        nombre = new JTextField();
        nombre.setText("");
        mainPanel.add(nombre, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        final JLabel label2 = new JLabel();
        label2.setText("Descripción:");
        mainPanel.add(label2, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label3 = new JLabel();
        label3.setText("Sitio web:");
        mainPanel.add(label3, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        desc = new JTextField();
        mainPanel.add(desc, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        sitioWeb = new JTextField();
        mainPanel.add(sitioWeb, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        aceptarButton = new JButton();
        aceptarButton.setText("Aceptar");
        mainPanel.add(aceptarButton, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        cancelarButton = new JButton();
        cancelarButton.setText("Cancelar");
        mainPanel.add(cancelarButton, new GridConstraints(3, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }

}