<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>uy.edu.eventos</groupId>
    <artifactId>eventos-uy</artifactId>
    <version>1.0-SNAPSHOT</version>
    <name>EventosUY</name>
    <description>Plataforma eventos.uy - Programacion de Aplicaciones</description>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.release>25</maven.compiler.release>
    </properties>

    <!--
        Por ahora no hay dependencias: las clases de dominio son Java puro.
        Cuando lleguemos a la capa de presentacion (Swing) vamos a sumar
        forms_rt y flatlaf.
    -->

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.14.0</version>
            </plugin>
        </plugins>
    </build>
</project>
